parameters:
#    acme_base.example.class: Acme\BaseBundle\Example

services:
#    acme_base.example:
#        class: %acme_base.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
