acme_infographic:
    resource: "@AcmeInfographicBundle/Controller/"
    type:     annotation
    prefix:   /

acme_anexo:
    resource: "@AcmeAnexoBundle/Controller/"
    type:     annotation
    prefix:   /

acme_search:
    resource: "@AcmeSearchBundle/Resources/config/routing.yml"
    prefix:   /

acme_base:
    resource: "@AcmeBaseBundle/Resources/config/routing.yml"
    prefix:   /
