# Acme/DemoBundle/Resources/config/admin.yml
services:
    sonata.admin.post:
        class: Acme\SearchBundle\Admin\PostAdmin
        tags:
          - name: sonata.admin 
            manager_type: orm 
            group: "Content" 
            label: "Post"
            label_catalogue: "AcmeDemoBundle" 
        
        arguments:
            - ~
            - Acme\SearchBundle\Entity\Post
            - ~
        calls:
            - [ setTranslationDomain, [AcmeSearchBundle]]

    sonata.admin.comment:
        class: Acme\SearchBundle\Admin\CommentAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Comment" }
        arguments:
            - ~
            - Acme\SearchBundle\Entity\Comment
            - ~
        calls:
            - [ setTranslationDomain, [AcmeSearchBundle]]
            