acme_search_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: AcmeSearchBundle:Default:index }

AcmeSearchBundle_post:
        resource: "@AcmeSearchBundle/Resources/config/routing/post.yml"
        prefix:   /post

