parameters:
#    acme_search.example.class: Acme\SearchBundle\Example

services:
#    acme_search.example:
#        class: %acme_search.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
