Acme\BaseBundle\Entity\Base:
  type: entity
  table: base
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    title:
      type: string  
    content:
        type: text
    createdAt:
      type: datetime
      name: created_at
    status:
      type: string
    author:
      type: string        